-- V10: MenuItem ↔ ModifierGroup assignment layer.
-- Connects the existing MenuItem (stored in the legacy `product` table) and
-- ModifierGroup aggregates so an item can offer many modifier groups and a
-- group can be reused across many items. ModifierGroup's own
-- min_selections / max_selections stay intrinsic defaults; no per-item
-- override lives here yet.
-- menu_item_modifier_group_assignment: many-to-many join carrying a
-- per-relationship display_order attribute. The (menu_item_id,
-- modifier_group_id) pair is unique so a group cannot be attached twice
-- to the same item. Removing the assignment leaves both the MenuItem and
-- the ModifierGroup intact.

CREATE TABLE menu_item_modifier_group_assignment (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    menu_item_id      BIGINT NOT NULL,
    modifier_group_id BIGINT NOT NULL,
    display_order     INT    NOT NULL,
    CONSTRAINT fk_mimg_assignment_item  FOREIGN KEY (menu_item_id) REFERENCES product(id),
    CONSTRAINT fk_mimg_assignment_group FOREIGN KEY (modifier_group_id) REFERENCES modifier_group(id),
    CONSTRAINT uk_menu_item_modifier_group UNIQUE (menu_item_id, modifier_group_id)
);
