-- V11: Organization and Store foundation.
-- organization: top-level tenant container (e.g. a restaurant chain or
-- franchise group). Name is required and unique.
-- stores: physical locations owned by exactly one organization.
--   * organization_id is NOT NULL so a store can never exist without an
--     owning organization; deleting an organization with stores is rejected
--     by the FK until its stores are removed first.
--   * name is the required human-readable label. It is NOT globally unique:
--     two stores may share a name within or across organizations.
--   * store_number is an optional human/business identifier that is unique
--     within an organization when present. PostgreSQL treats NULL values in
--     a UNIQUE index as distinct, so an organization may own multiple
--     stores with a NULL store_number.
--   * Address, contact, and timezone columns live directly on the store
--     because the tenancy foundation has no separate Address entity yet.
-- Table name uses the plural "stores" following the existing "orders" and
-- "payments" convention so the reserved-looking word "store" is never
-- required as a bare identifier.

CREATE TABLE organization (
    id     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name   VARCHAR(255) NOT NULL,
    active BOOLEAN      NOT NULL DEFAULT true,
    CONSTRAINT uk_organization_name UNIQUE (name)
);

CREATE TABLE stores (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organization_id BIGINT       NOT NULL,
    store_number    VARCHAR(64),
    name            VARCHAR(255) NOT NULL,
    active          BOOLEAN      NOT NULL DEFAULT true,
    country         VARCHAR(2)   NOT NULL,
    state_province  VARCHAR(80)  NOT NULL,
    city            VARCHAR(80)  NOT NULL,
    address_line1   VARCHAR(200) NOT NULL,
    address_line2   VARCHAR(200),
    postal_code     VARCHAR(20)  NOT NULL,
    phone_number    VARCHAR(32),
    email           VARCHAR(255),
    timezone        VARCHAR(64)  NOT NULL,
    CONSTRAINT fk_stores_organization FOREIGN KEY (organization_id) REFERENCES organization(id),
    CONSTRAINT uk_stores_organization_number UNIQUE (organization_id, store_number)
);
