-- V12: Employee group foundation.
-- employee_group: a node in a per-organization employee group hierarchy.
--   * organization_id is NOT NULL so a group can never exist without an
--     owning organization; deleting an organization with groups is rejected
--     by fk_employee_group_organization until its groups are removed first.
--   * parent_employee_group_id is optional; NULL marks a root group. The
--     composite fk_employee_group_parent foreign key on
--     (parent_employee_group_id, organization_id) referencing
--     (id, organization_id) enforces at the database level that a parent and
--     its children always belong to the same organization, alongside the
--     service-layer check. The uk_employee_group_id_organization unique
--     constraint exists to support that composite foreign key.
--   * chk_employee_group_not_self_parent blocks a row from being its own
--     parent; indirect cycles are rejected by the service layer because they
--     cannot be expressed as a row-level constraint.
--   * name is required but not unique: two groups may share a name within
--     or across organizations.
-- The two explicit indexes cover the foreign key columns, which PostgreSQL
-- does not index automatically: organization-scoped listings and the
-- delete guards read organization_id, while child listings read
-- parent_employee_group_id.

CREATE TABLE employee_group (
    id                       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organization_id          BIGINT       NOT NULL,
    parent_employee_group_id BIGINT,
    name                     VARCHAR(255) NOT NULL,
    active                   BOOLEAN      NOT NULL DEFAULT true,
    CONSTRAINT fk_employee_group_organization FOREIGN KEY (organization_id) REFERENCES organization(id),
    CONSTRAINT uk_employee_group_id_organization UNIQUE (id, organization_id),
    CONSTRAINT fk_employee_group_parent FOREIGN KEY (parent_employee_group_id, organization_id) REFERENCES employee_group (id, organization_id),
    CONSTRAINT chk_employee_group_not_self_parent CHECK (parent_employee_group_id IS NULL OR parent_employee_group_id <> id)
);

CREATE INDEX idx_employee_group_organization_id ON employee_group (organization_id);
CREATE INDEX idx_employee_group_parent_id ON employee_group (parent_employee_group_id);
