-- V13: Employee foundation.
-- employee: an individual who works for exactly one organization. Employee
-- group membership, permissions, inherited configuration, store
-- assignments, and authorization are intentionally not part of this
-- foundation.
--   * organization_id is NOT NULL so an employee can never exist without an
--     owning organization; deleting an organization with employees is
--     rejected by fk_employee_organization until its employees are removed
--     first.
--   * name is the required human-readable label. It is NOT unique: two
--     employees may share a name within or across organizations.
--   * email is optional and unique within the owning organization when
--     present through uk_employee_organization_email on (organization_id,
--     email). PostgreSQL treats NULL values in a UNIQUE constraint as
--     distinct, so an organization may employ many people without an email
--     address. Emails are stored as submitted after trimming and are not
--     case-folded, matching the stores.email convention.
--   * The explicit index covers the organization_id foreign key column used
--     by the organization delete guard and organization-scoped lookups.
-- Table name stays singular "employee" like "organization"/"menu": the word
-- is not reserved in PostgreSQL and matches Hibernate's default mapping for
-- the single-word entity class.

CREATE TABLE employee (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organization_id BIGINT       NOT NULL,
    name            VARCHAR(255) NOT NULL,
    email           VARCHAR(255),
    active          BOOLEAN      NOT NULL DEFAULT true,
    CONSTRAINT fk_employee_organization FOREIGN KEY (organization_id) REFERENCES organization(id),
    CONSTRAINT uk_employee_organization_email UNIQUE (organization_id, email)
);

CREATE INDEX idx_employee_organization_id ON employee (organization_id);
