-- V14: Employee ↔ EmployeeGroup membership (many-to-many).
-- An employee can belong to many groups and a group can contain many
-- employees, but every membership row ties an employee and a group that
-- share the same owning Organization.
-- employee_group_membership:
--   * uk_employee_group_membership on (employee_id, employee_group_id) is
--     the database-level duplicate prevention for a pair; the service layer
--     also refuses to re-add an existing membership so PUT is idempotent.
--   * organization_id is denormalized onto the row so two composite foreign
--     keys can pin both sides to a single organization at the database
--     level: fk_egm_employee on (employee_id, organization_id) referencing
--     employee (id, organization_id) and fk_egm_employee_group on
--     (employee_group_id, organization_id) referencing
--     employee_group (id, organization_id). Together they make a
--     cross-organization membership impossible to write even if the service
--     check is bypassed.
--   * uk_employee_id_organization is added on employee to support the
--     composite employee FK (employee_group already carries the matching
--     uk_employee_group_id_organization from V12).
--   * The (employee_id, employee_group_id) unique index already covers the
--     "list an employee's groups" lookup through its leading column, so an
--     explicit index is only needed for the "list a group's employees"
--     direction on employee_group_id.
-- Deleting an employee or a group that still carries memberships is
-- rejected by the foreign keys and pre-empted by the service-layer delete
-- guards, so no membership row can dangle.

ALTER TABLE employee ADD CONSTRAINT uk_employee_id_organization UNIQUE (id, organization_id);

CREATE TABLE employee_group_membership (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organization_id   BIGINT NOT NULL,
    employee_id       BIGINT NOT NULL,
    employee_group_id BIGINT NOT NULL,
    CONSTRAINT uk_employee_group_membership UNIQUE (employee_id, employee_group_id),
    CONSTRAINT fk_egm_employee FOREIGN KEY (employee_id, organization_id) REFERENCES employee (id, organization_id),
    CONSTRAINT fk_egm_employee_group FOREIGN KEY (employee_group_id, organization_id) REFERENCES employee_group (id, organization_id)
);

CREATE INDEX idx_egm_employee_group_id ON employee_group_membership (employee_group_id);
