-- V1: create the product table matching the Product JPA entity.
-- id:    identity column implementing GenerationType.IDENTITY.
-- price: exact monetary column NUMERIC(10,2) (cents) per the entity mapping.
-- name and price are NOT NULL, matching the API/service invariants
-- (blank name and missing/negative prices are rejected at the boundary).

CREATE TABLE product (
    id    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name  VARCHAR(255) NOT NULL,
    price NUMERIC(10, 2) NOT NULL
);
