-- V3: product categories.
-- category: standalone table; name is required and unique.
-- product.category_id: optional foreign key so a product can reference a
-- category. The column is nullable: existing products keep working without
-- one until a category is assigned, so no rows are rewritten.

CREATE TABLE category (
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    CONSTRAINT uk_category_name UNIQUE (name)
);

ALTER TABLE product ADD COLUMN category_id BIGINT;

ALTER TABLE product
    ADD CONSTRAINT fk_product_category FOREIGN KEY (category_id) REFERENCES category (id);
