-- V4: orders and order lines.
-- orders: top-level order with status and creation timestamp.
-- Table name is "orders" (not "order") to avoid the SQL reserved word.
-- order_line: individual lines referencing a product, capturing the
-- product's current price as unit_price at the time the order was placed.
-- Both foreign keys are NOT NULL: every line must belong to an order and
-- reference a product.

CREATE TABLE orders (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    status     VARCHAR(16)  NOT NULL,
    created_at TIMESTAMP    NOT NULL
);

CREATE TABLE order_line (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id   BIGINT        NOT NULL,
    product_id BIGINT        NOT NULL,
    quantity   INT           NOT NULL,
    unit_price NUMERIC(10,2) NOT NULL,
    CONSTRAINT fk_order_line_order FOREIGN KEY (order_id) REFERENCES orders(id),
    CONSTRAINT fk_order_line_product FOREIGN KEY (product_id) REFERENCES product(id)
);
