-- V7: Menu and MenuGroup foundation.
-- menu: top-level container for a set of menu groups (e.g. "Lunch", "Dinner").
-- menu_group: reusable collection of menu items (e.g. "Appetizers"). A group
-- can appear in multiple menus.
-- menu_group_assignment: many-to-many between menu and menu_group with an
-- per-relationship display_order attribute. The pair (menu_id, menu_group_id)
-- is unique so a group cannot be assigned to the same menu twice.

CREATE TABLE menu (
    id     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name   VARCHAR(255) NOT NULL,
    active BOOLEAN      NOT NULL DEFAULT true,
    CONSTRAINT uk_menu_name UNIQUE (name)
);

CREATE TABLE menu_group (
    id     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name   VARCHAR(255) NOT NULL,
    active BOOLEAN      NOT NULL DEFAULT true,
    CONSTRAINT uk_menu_group_name UNIQUE (name)
);

CREATE TABLE menu_group_assignment (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    menu_id       BIGINT NOT NULL,
    menu_group_id BIGINT NOT NULL,
    display_order INT    NOT NULL,
    CONSTRAINT fk_menu_group_assignment_menu FOREIGN KEY (menu_id) REFERENCES menu(id),
    CONSTRAINT fk_menu_group_assignment_group FOREIGN KEY (menu_group_id) REFERENCES menu_group(id),
    CONSTRAINT uk_menu_group_assignment UNIQUE (menu_id, menu_group_id)
);
