-- V8: MenuGroup <-> MenuItem assignment.
-- menu_item_assignment records that a MenuItem is displayed inside a
-- MenuGroup at a specific display_order position. The relationship is
-- intentionally many-to-many: the same MenuItem may appear in many groups
-- (reusable) and the same MenuGroup may contain many items. The
-- (menu_group_id, menu_item_id) pair is unique so an item cannot be added
-- to the same group twice. The MenuItem foreign key targets the "product"
-- table because the MenuItem entity keeps its original physical schema
-- (see MenuItem @Table(name = "product")).

CREATE TABLE menu_item_assignment (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    menu_group_id BIGINT NOT NULL,
    menu_item_id  BIGINT NOT NULL,
    display_order INT    NOT NULL,
    CONSTRAINT fk_menu_item_assignment_group FOREIGN KEY (menu_group_id) REFERENCES menu_group(id),
    CONSTRAINT fk_menu_item_assignment_item  FOREIGN KEY (menu_item_id) REFERENCES product(id),
    CONSTRAINT uk_menu_item_assignment UNIQUE (menu_group_id, menu_item_id)
);
