-- V9: Modifier and ModifierGroup foundation.
-- modifier_group: a named container of selectable add-ons with a
-- selection policy (min_selections / max_selections). The group owns the
-- assignment rows; deleting a group removes its assignments but never the
-- underlying modifiers.
-- modifier: a selectable option with a price adjustment. Modifiers are
-- reusable across many modifier groups (e.g. "Extra cheese" can appear in
-- both "Pizza toppings" and "Burger toppings"), so the name is NOT
-- enforced unique at the database level.
-- modifier_group_assignment: many-to-many between modifier_group and
-- modifier carrying a per-relationship display_order attribute. The
-- (modifier_group_id, modifier_id) pair is unique so a modifier cannot
-- appear twice inside the same group.

CREATE TABLE modifier_group (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name           VARCHAR(255) NOT NULL,
    min_selections INT          NOT NULL DEFAULT 0,
    max_selections INT          NOT NULL DEFAULT 0,
    active         BOOLEAN      NOT NULL DEFAULT true,
    CONSTRAINT uk_modifier_group_name UNIQUE (name),
    CONSTRAINT chk_modifier_group_min_non_negative CHECK (min_selections >= 0),
    CONSTRAINT chk_modifier_group_max_gte_min      CHECK (max_selections >= min_selections)
);

CREATE TABLE modifier (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name             VARCHAR(255)   NOT NULL,
    price_adjustment NUMERIC(10, 2) NOT NULL DEFAULT 0,
    active           BOOLEAN        NOT NULL DEFAULT true
);

CREATE TABLE modifier_group_assignment (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    modifier_group_id BIGINT NOT NULL,
    modifier_id       BIGINT NOT NULL,
    display_order     INT    NOT NULL,
    CONSTRAINT fk_modifier_group_assignment_group FOREIGN KEY (modifier_group_id) REFERENCES modifier_group(id),
    CONSTRAINT fk_modifier_group_assignment_modifier FOREIGN KEY (modifier_id) REFERENCES modifier(id),
    CONSTRAINT uk_modifier_group_assignment UNIQUE (modifier_group_id, modifier_id)
);
